name: manager_app
description: LiQR's Manager application.
version: 0.0.19+53

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
#  sdk: ">=2.9.0-14.1.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.5+1
  shared_preferences: ^0.5.7+1
  flutter_plugin_pdf_viewer: ^1.0.7
  custom_switch: ^0.0.1
  interactive_webview: ^0.1.2
  image_picker: ^0.6.7+2
  audioplayers: ^0.15.1
  socket_io_client: ^0.9.10
  url_launcher: ^5.5.0
  fluttertoast: ^7.0.1
  native_pdf_renderer: ^2.3.2
#  dio: ^3.0.9
  photo_view: ^0.9.2
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter
#  adhara_socket_io: ^0.4.1
  fl_chart: ^0.8.7
  http: ^0.12.0+4
  date_format: ^1.0.8


flutter:
  uses-material-design: true

  assets:
      - assets/icons/
      
      - assets/sound.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600






