name: adhara_socket_io_example
description: Demonstrates how to use the adhara_socket_io plugin.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.5+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  adhara_socket_io: ^0.4.1
  fl_chart: ^0.8.7
  http: ^0.12.0+4
  date_format: ^1.0.8


flutter:
  uses-material-design: true

  assets:
      - assets/icons/
